class HelloWorld {
    public static void main(String[] args) {
        int x = 5;
        int y = 8;
        int sum = x + y;
        int ginomeno = x % y;
        int pollaplasiasmos = x * y;
        System.out.println(sum);
        System.out.println(pollaplasiasmos);
        System.out.println(ginomeno);
    }
}
public static void main (String[] args) {
int x=5;
int y=6;
system.out.printin(x+y);
}
}

class helloworld {
public static void main(string[] args){
int x=5;
int y=8;
int sum=x+y;
int ginomeno=
int pollaplasiasmos=
system.out.printin(sum);
}
]
