public class Car {
    private String brand;
    private String model;

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public void setModel(String model) {
        this.model = model;
    }
}
 public class Car {
        public String getBrand() {
            return brand;
        }

        public String getModel() {
            return model;
        }
    }


public class main {
public static void main (String[] args) {
                                                                  DRALD REdAY
    Car c2 = new Car();                          VOOEL: CLIO

    cl.setBrand("Nissan");
    cl.settlodel("GT-R");
    c2.setBrand("RENAULT");
    c2.settlodel("CLIC");
}
}

System.out.println("BRAND: " + cl.getBrand());
System.out.println("MODEL: " + cl.getModel());

System.out.println("\n-=--=== A B EÂ§oSeg MpoÂ¡ ===---=-");
System.out.println("BRAND: " + c2.getBrand());

System.out.println("MODEL: " + c2.getModel());

System.out.println("VEHICLE: GT-R");

System.out.println("BRAND: RENAULT");
System.out.println("MODEL: CLIO");