 class HelloWorld {
    public static void main(String[] args) {
        int eisodima=10000;
        
        float foros=0;
        
        if(eisodima<5000)
          { 
            
        }
        if(eisodima>=5000 && eisodima<=10000) 
        {
         foros=(5/100;
    }
    if(eisodima>10000 && eisodima<=3000){
        foros=15/100;
    }
    if(eisodima>30000){
        foros=35/100;
    }
         System.out.println("eisodima= "+eisodima+" foros= "+foros);
    }
}


public class RunProgram {
    public static void main(String[] args) {
        int number=5, i, result=1;
        for(i=1; i<number; i++)
        {
            result=result*i;
        }
        System.out.println("result="+ result);
     
        
    }
}