import java.utill.Scanner;
import java.lang.Math;

 public class Temperature
{
    public static void main(String[] args){
            int f;
            double c;
            Scanner in = new Scanner(System.in);
            System.out.println("enter f value: ");
            f=in.nextInt();
    
            c=5*(F-32)/9;
            System.out.println("f="+"f"+ --------->C= "+c);
    
    }
  
    
}