public class BoatProgram            κλασση της βαρκας αρχικοποιηση στοιχειων 
{
    Boat Highspeed= new Boat("Green", 4, 80000);
    Highspeed.showinfo(); 
    Highspeed.setPrice(88000);
    
}
public class Runprogram{ τρεχει και εκτελει το προγραμμα 
    public static void main(String[] args){
        System.out.println("result="+result);
    }
}
    }
}



 public class Familymember
 {
    protected String surname;
 }
 
 
 public class father extends Familymember {
     protected String name;
 }  
 
 public class mother extends Familymember{
     protected String name;
 }
 
 public class kid extends Familymember{
     protected String name;
 }
 

